= IRC Client Library for Arduino image:https://travis-ci.org/fredimachado/ArduinoIRC.svg?branch=master["Build Status", link="https://travis-ci.org/fredimachado/ArduinoIRC"]

Connects your arduino project to an IRC server.

== Features

* Easy connection to an IRC server through a Client implementation;
* Receive parsed IRC messages through a callback function;
* Send raw messages to the server or messages to a channel or user;
* Supports Twitch Chat

== Usage

See the examples...

== Contribution

Just send a pull request! :)

== License

Copyright (c) 2016 Fredi Machado. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
